version: "3.2"
services:
  back:
    image: "${IMAGE_TAG}"
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
      placement:
        constraints:
          - "${PLACEMENT}"
    env_file:
      - "${ENV_FILE}"
    logging:
      driver: "json-file"
      options:
        max-file: 5
        max-size: 10m      
    networks:
      default:
        aliases:
          - "${DOCKER_STACK}-hostname"
#    volumes:
#      - type: bind
#        source: /root/ssl/certificate.crt
#        target: /tomcat.crt
#      - type: bind
#        source: /root/ssl/private.key
#        target: /tomcat.key
#      - type: bind
#        source: /root/ssl/ca_bundle.crt
#        target: /ca_tomcat.crt

networks:
  default:
    external:
      name: webnet
