#security:
#  require-ssl: false
server:
  port: 80
#  ssl:
#    key-store: keystore.jks
#    key-store-password: ${SSLPASS}
#    keyStoreType: JKS
#    keyAlias: tomcat
spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: ${DBURL}
    username: ${DBUSER}
    password: ${DBPASS}
    tomcat:
      initial-size: 10
      max-active: 10
      max-idle: 10
      min-idle: 10
  main:
    allow-bean-definition-overriding: true
mybatis:
  typeAliasesPackage: pe.mm.reception.core.model
  mapper-locations: classpath*:/mybatis/**/*Mapper.xml

loggin:
  level:
    pe.mentor.monitor.core.service.microservice: DEBUG

app:
  redis:
    url: ${REDISURL}
    password: ${REDISPASS}